name: Node CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [4.x, 6.x, 8.x, 9.x, 10.x, 12.x, 13.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Mocha
      run: |
        npm install
        npm run test:mocha
      env:
        CI: true

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Linting
      uses: goto-bus-stop/standard-action@v1
      with:
        annotate: true
        files: '{src/**/*.js,test/**/*.js}'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
